### PR TITLE
add 'put_string' as a compiler primitive

### PR DESCRIPTION
**Pull request by emturner**
Add compiler primitive 'put' to allow printing without newline

### CODE REVIEW

**Comment by emturner** [comment]
If/when this goes in, will try and update the IO functions in lib later this evening :)

**Comment by MaiaVictor** [comment]
Thanks! But can you rename it to `put_line`?

**Comment by emturner** [comment]
> Thanks! But we should rename it to `put_something`, because `put` is too broad. Not sure what word we could use.

could call it put_string ?

**Comment by MaiaVictor** [comment]
Yeah, considering Haskell's equivalent is `putStr`, and since we use underscores and avoid abbreviations, `put_string` seems reasonable.

**Pull request merged**
